# Compose file for development environment
version: "3.8"

services:
  back:
    image: rmapps-back:v1
    restart: always
    volumes:
      - .:/app
    env_file:
      - ./.env
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_DATABASE} -h localhost -p ${DB_PORT}"]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

volumes:
  postgres_data:
